import PDFDocument from 'pdfkit';
import { PLACE_DETAILS } from './constants';

interface PDFGeneratorProps {
  email: string;
  placeToVisit: string;
  tripType: string;
  transportation: string;
  currentLocation: string;
  distance: string;
  placeDetails: typeof PLACE_DETAILS[keyof typeof PLACE_DETAILS];
}

export async function generatePDF(data: PDFGeneratorProps): Promise<Buffer> {
  return new Promise((resolve) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 50, right: 50 }
    });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    // Header
    doc
      .fillColor('#1a365d')
      .fontSize(28)
      .font('Helvetica-Bold')
      .text('Your Satara Trip Plan', { align: 'center' })
      .moveDown();

    // Destination header with styling
    doc
      .fillColor('#2563eb')
      .fontSize(24)
      .text(data.placeToVisit, { align: 'center' })
      .moveDown();

    // Trip Overview Box
    drawBox(doc, () => {
      doc
        .fillColor('#1a365d')
        .fontSize(16)
        .font('Helvetica-Bold')
        .text('Trip Overview')
        .moveDown(0.5)
        .fontSize(12)
        .font('Helvetica')
        .fillColor('#4a5568')
        .text(`Trip Type: ${data.tripType}`)
        .text(`Transportation: ${data.transportation}`)
        .text(`Distance: ${data.distance}`);
    });

    // Description
    doc
      .moveDown()
      .fillColor('#1a365d')
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('About the Destination')
      .moveDown(0.5)
      .fontSize(12)
      .font('Helvetica')
      .fillColor('#4a5568')
      .text(data.placeDetails.description, { align: 'justify' })
      .moveDown();

    // Transportation Details Box
    drawBox(doc, () => {
      doc
        .fillColor('#1a365d')
        .fontSize(16)
        .font('Helvetica-Bold')
        .text('How to Reach')
        .moveDown(0.5)
        .fontSize(12)
        .font('Helvetica')
        .fillColor('#4a5568')
        .text(`Nearest Airport: ${data.placeDetails.nearestAirport}`)
        .text(`Nearest Railway: ${data.placeDetails.nearestRailway}`)
        .text(`Nearest Bus Stop: ${data.placeDetails.nearestBusStop}`);
    });

    // Must Visit Spots
    doc.moveDown();
    drawBox(doc, () => {
      doc
        .fillColor('#1a365d')
        .fontSize(16)
        .font('Helvetica-Bold')
        .text('Must-Visit Spots')
        .moveDown(0.5)
        .fontSize(12)
        .font('Helvetica')
        .fillColor('#4a5568');

      data.placeDetails.mustVisit.forEach((spot) => {
        doc.text(`• ${spot}`);
      });
    });

    // Travel Tips
    doc.moveDown();
    drawBox(doc, () => {
      doc
        .fillColor('#1a365d')
        .fontSize(16)
        .font('Helvetica-Bold')
        .text('Travel Tips')
        .moveDown(0.5)
        .fontSize(12)
        .font('Helvetica')
        .fillColor('#4a5568');

      data.placeDetails.tips.forEach((tip) => {
        doc.text(`• ${tip}`);
      });
    });

    // Footer
    doc
      .moveDown()
      .fontSize(10)
      .fillColor('#718096')
      .text('Generated by Satara Tourism', { align: 'center' })
      .text(`Visit Timing: ${data.placeDetails.timings} | Entry Fee: ${data.placeDetails.entryFee}`, { align: 'center' });

    doc.end();
  });
}

function drawBox(doc: PDFKit.PDFDocument, content: () => void) {
  const initialY = doc.y;
  content();
  const finalY = doc.y;
  
  doc
    .rect(45, initialY - 5, 505, finalY - initialY + 10)
    .fillColor('#f7fafc')
    .fill()
    .strokeColor('#e2e8f0')
    .stroke();
    
  doc.y = initialY;
  content();
}

